apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    {{- with .Values.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
    # - port: 80
      targetPort: 3000
      protocol: TCP
      # nodePort: 30000
  selector:
    {{- with .Values.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
